// auth types
export const AUTHENTICATE = 'authenticate';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';

export const DEAUTHENTICATE = 'deauthenticate';

// menu categories
export const MENU_CATEGORIES = "MENU_CATEGORIES"

// product types 
export const LATEST_PRODUCTS = "LATEST_PRODUCTS"
export const PRODUCT_DETAILS = "PRODUCT_DETAILS"
export const GET_BRANDS = "GET_BRANDS"
export const PRODUCT_ERROR = "PRODUCT_ERROR"
export const PRODUCT_BY_CATEGORY = "PRODUCT_BY_CATEGORY"
export const PRODUCT_QA = "PRODUCT_QA"
export const POST_QUESTION = "POST_QUESTION"
export const PRODUCT_REVIEWS = "PRODUCT_REVIEWS"
export const POST_PRODUCT_REVIEWS = "POST_PRODUCT_REVIEWS"

// search
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"
export const SEARCH_FILTER = "SEARCH_FILTER"
export const SEARCH_ERROR = "SEARCH_ERROR"
export const SEARCH_KEYWORD = "SEARCH_KEYWORD"

// user
export const USER_PROFILE = "USER_PROFILE"
export const ADD_ADDRESS = "ADD_ADDRESS"
export const EDIT_ADDRESS = "EDIT_ADDRESS"
export const TOGGLE_ACTIVE_ADDRESS = "TOGGLE_ACTIVE_ADDRESS"
export const USER_ERROR = "USER_ERROR"
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE"
export const MY_PROFILE_REVIEWS = "MY_PROFILE_REVIEWS"

// error
export const GLOBAL_ERROR = "GLOBAL_ERROR"

//loading
export const LATEST_LOADING = 'LATEST_LOADING'

// other
export const GET_BANNER_IMAGES = 'GET_BANNER_IMAGES'

//cart
export const CART_PRODUCTS = 'CART_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const EDIT_CART_QTY = 'EDIT_CART_QTY'
export const STORE_CHECKOUT_ITEMS = 'STORE_CHECKOUT_ITEMS'
export const STORE_CART_ITEMS = 'STORE_CART_ITEMS'

//wishlist
export const ADD_WISHLIST_ITEMS = 'ADD_WISHLIST_ITEMS'
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST'
export const GET_WISHLIST_ITEMS = 'GET_WISHLIST_ITEMS'

//orders
export const GET_ORDERS = 'GET_ORDERS'
export const GET_ORDERS_STATUSES = 'GET_ORDERS_STATUSES'
export const PLACE_ORDER = 'PLACE_ORDER'
export const GET_SHIPPING_CHARGE = 'GET_SHIPPING_CHARGE'

