const tintColor = '#48b5dc';

export default {
  tintColor,
  grayColor: "#66727e",
  backgroundColor: '#86909a',
  bannerColor: "#2978a0",
  filledColor: "#2978a0",
  initialColor: "#DCDCDC",
  _filledColor: "#77ba99",
  cardColor: "#f1f7ff",
  tabIconDefault: '#ccc',
  headerTintColor: "#fff",
  activeTintColor: tintColor,
  inactiveTintColor: "#000",
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  normalScreenHeaderSize: 21,
  smallScreenHeaderSize: 16,
  normalScreenDescriptionSize: 14,
  smallScreenDescriptionSize: 10,
};